### ISSUE TITLE
Chromecast 3

### ISSUE THREAD

**Issue by arist0v** [mrstegeman/chromecast-adapter#10]
Chromecast 3 didn't seem to work.

**Comment by mrstegeman** [comment]
What doesn't work, exactly? I don't have a device to test with.

There may be an issue with the library: https://github.com/thibauts/node-castv2-client

**Comment by arist0v** [comment]
It detect the device, i can add it, but can't change or receive any data
from it

Le mer. 30 déc. 2020 02 h 14, Michael Stegeman <notifications@github.com> a
écrit :

**Comment by mrstegeman** [comment]
That was my assumption. Definitely sounds like an issue with the library.

**Comment by arist0v** [comment]
What could i do to help resolve this issue? Open a ticket in the library
github?

Le mer. 30 déc. 2020 11 h 48, Michael Stegeman <notifications@github.com> a
écrit :

**Comment by mrstegeman** [comment]
Yes, please do that. If we don't get a response, I should be able to rewrite this adapter in Python and use a different library.
